"""add_bargain_and_chat_tables

Revision ID: 6f75bf8eb7e8
Revises: e760f2b85988
Create Date: 2026-03-23 16:57:25.446866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f75bf8eb7e8'
down_revision: Union[str, Sequence[str], None] = 'e760f2b85988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bargainsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gadget_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buyer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('current_offer', sa.Float(), nullable=False),
    sa.Column('offered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gadget_id'], ['gadget.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bargainsession_buyer_id'), 'bargainsession', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_bargainsession_gadget_id'), 'bargainsession', ['gadget_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gadget_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gadget_id'], ['gadget.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_gadget_id'), 'chatmessage', ['gadget_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_receiver_id'), 'chatmessage', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_sender_id'), 'chatmessage', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessage_sender_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_receiver_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_gadget_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_bargainsession_gadget_id'), table_name='bargainsession')
    op.drop_index(op.f('ix_bargainsession_buyer_id'), table_name='bargainsession')
    op.drop_table('bargainsession')
    # ### end Alembic commands ###
