"""actually add review table

Revision ID: b8ce0cc1189e
Revises: 170625e25a22
Create Date: 2026-03-24 11:53:23.068552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8ce0cc1189e'
down_revision: Union[str, Sequence[str], None] = '170625e25a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gadget_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gadget_id'], ['gadget.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_gadget_id'), 'review', ['gadget_id'], unique=False)
    op.create_index(op.f('ix_review_order_id'), 'review', ['order_id'], unique=False)
    op.create_index(op.f('ix_review_reviewer_id'), 'review', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_reviewer_id'), table_name='review')
    op.drop_index(op.f('ix_review_order_id'), table_name='review')
    op.drop_index(op.f('ix_review_gadget_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
